{{ if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "instana-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}