{{ if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "instana-agent.serviceAccountName" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
{{- end }}